export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const REMOVE_USERS_REQUESTED = "REMOVE_USERS_REQUESTED";
export const REMOVE_USERS_SUCCESS = "REMOVE_USERS_SUCCESS";
export const REMOVE_USERS_FAILED = "REMOVE_USERS_ERROR";
